import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { applyPlan, prepareApply, rollbackPlan } from "./apply.mjs";
import { captureSkill } from "./source.mjs";

test("pins a draft, rejects concurrent changes, applies complete variants and rolls back without touching comments", async context => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "skill-apply-"));
  context.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const directory = path.join(root, "skills/example");
  fs.mkdirSync(path.join(directory, "variants"), { recursive: true });
  const original = "---\nname: example\ndescription: Fixture\n---\nOriginal\n";
  for (const profile of ["gpt-5.6", "gpt-6-astra", "claude-fable-5.1", "claude-opus-5"]) fs.writeFileSync(path.join(directory, "variants", profile + ".md"), original);
  fs.symlinkSync(path.join(directory, "variants/gpt-5.6.md"), path.join(directory, "SKILL.md"));
  const record = { source: captureSkill({ name: "example", directory }, "head"), draft: { revision: 2, content: { status: "ready", decision: "edit", master: "Updated", notes: "Keep this comment", files: {}, reviewedFiles: [] } } };
  const readDetail = async () => record;
  const plan = path.join(root, "plan");
  await prepareApply({ name: "example", revision: 2, directory: plan, root, readDetail });
  for (const profile of ["gpt-5.6", "gpt-6-astra", "claude-fable-5.1", "claude-opus-5"]) fs.writeFileSync(path.join(plan, "candidate/variants", profile + ".md"), original.replace("Original", "Updated"));
  record.draft.revision = 3;
  await assert.rejects(applyPlan(plan, readDetail), /draft changed/);
  assert.equal(fs.readFileSync(path.join(directory, "SKILL.md"), "utf8"), original);
  record.draft.revision = 2;
  fs.writeFileSync(path.join(directory, "user-edit.txt"), "new work");
  await assert.rejects(applyPlan(plan, readDetail), /Source changed/);
  fs.unlinkSync(path.join(directory, "user-edit.txt"));
  const applied = await applyPlan(plan, readDetail);
  assert.equal(applied.revision, 2);
  assert.match(fs.readFileSync(path.join(directory, "SKILL.md"), "utf8"), /Updated/);
  fs.writeFileSync(path.join(directory, "later.txt"), "later edit");
  assert.throws(() => rollbackPlan(plan), /edited later/);
  fs.unlinkSync(path.join(directory, "later.txt"));
  rollbackPlan(plan);
  assert.equal(fs.readFileSync(path.join(directory, "SKILL.md"), "utf8"), original);
  assert.equal(record.draft.content.notes, "Keep this comment");
  assert.equal(record.draft.revision, 2);
});
