import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { applyPlan, prepareApply, rollbackPlan } from "./apply.mjs";
import { captureSkill } from "./source.mjs";

test("pins a draft, rejects intervening changes and rolls back replaced files without touching comments", async context => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "skill-apply-"));
  context.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const directory = path.join(root, "skills/example");
  fs.mkdirSync(path.join(directory, "variants"), { recursive: true });
  const original = "---\nname: example\ndescription: Fixture\n---\nOriginal\n";
  const profiles = ["gpt-6", "claude-fable-5.1", "claude-opus-5.5"];
  for (const profile of profiles) {
    const variant = path.join(directory, "variants", profile + ".md");
    if (profile !== "claude-opus-5.5") fs.writeFileSync(variant, original);
    else fs.symlinkSync("claude-fable-5.1.md", variant);
  }
  fs.symlinkSync(path.join(directory, "variants/gpt-6.md"), path.join(directory, "SKILL.md"));
  const master = original.replace("Original\n", "Audited café → baseline\r\nKeep trailing spaces.  ");
  const record = { source: captureSkill({ name: "example", directory }, "head"), draft: { revision: 2, content: { status: "ready", decision: "edit", master, notes: "Keep this comment", files: {}, reviewedFiles: [] } } };
  const readDetail = async () => record;
  const plan = path.join(root, "plan");
  await prepareApply({ name: "example", revision: 2, directory: plan, root, readDetail });
  const candidateBase = path.join(plan, "candidate/BASE.md");
  assert.equal(fs.readFileSync(candidateBase, "utf8"), master);
  for (const profile of profiles) fs.writeFileSync(path.join(plan, "candidate/variants", profile + ".md"), original.replace("Original", "Updated"));
  fs.writeFileSync(candidateBase, "Changed without approval");
  await assert.rejects(applyPlan(plan, readDetail), /exact pinned audit master/);
  assert.equal(fs.existsSync(path.join(directory, "BASE.md")), false);
  assert.equal(fs.readFileSync(path.join(directory, "SKILL.md"), "utf8"), original);
  fs.writeFileSync(candidateBase, master);
  record.draft.revision = 3;
  await assert.rejects(applyPlan(plan, readDetail), /draft changed/);
  assert.equal(fs.readFileSync(path.join(directory, "SKILL.md"), "utf8"), original);
  record.draft.revision = 2;
  fs.writeFileSync(path.join(directory, "user-edit.txt"), "new work");
  await assert.rejects(applyPlan(plan, readDetail), /Source changed/);
  fs.unlinkSync(path.join(directory, "user-edit.txt"));
  await applyPlan(plan, readDetail);
  assert.match(fs.readFileSync(path.join(directory, "SKILL.md"), "utf8"), /Updated/);
  assert.equal(fs.readFileSync(path.join(directory, "BASE.md"), "utf8"), master);
  assert.equal(fs.readlinkSync(path.join(directory, "variants/claude-opus-5.5.md")), "claude-fable-5.1.md");
  fs.writeFileSync(path.join(directory, "later.txt"), "later edit");
  assert.throws(() => rollbackPlan(plan), /edited later/);
  fs.unlinkSync(path.join(directory, "later.txt"));
  rollbackPlan(plan);
  assert.equal(fs.readFileSync(path.join(directory, "SKILL.md"), "utf8"), original);
  assert.equal(fs.readlinkSync(path.join(directory, "variants/claude-opus-5.5.md")), "claude-fable-5.1.md");
  assert.equal(fs.existsSync(path.join(directory, "BASE.md")), false);
  assert.equal(record.draft.content.notes, "Keep this comment");
});
