export { default as base } from "./presets/base.mjs";
export { default as jest } from "./presets/jest.mjs";
export { default as playwright } from "./presets/playwright.mjs";
export { default as prisma } from "./presets/prisma.mjs";
export { default as reactNative } from "./presets/react-native.mjs";
export { default as react } from "./presets/react.mjs";
export { default as tailwind } from "./presets/tailwind.mjs";
export { default as tanstackQuery } from "./presets/tanstack-query.mjs";
export { default as typescript } from "./presets/typescript.mjs";
export { default as vitest } from "./presets/vitest.mjs";
export { default as zod } from "./presets/zod.mjs";
export { standards } from "./standards-plugin.mjs";
