import tsParser from "@typescript-eslint/parser";
import { RuleTester } from "eslint";
import { describe, it } from "vitest";

import rule from "./no-brittle-test-style-assertions.mjs";

RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester({
	languageOptions: { parser: tsParser, sourceType: "module", parserOptions: { ecmaVersion: 2022 } },
});

ruleTester.run("no-brittle-test-style-assertions", rule, {
	valid: [
		{
			name: "resolves only the accessed locator-helper property (2)",
			code: '\n\t\t\tconst targets = {\n\t\t\t\tcard: () => page.locator(".w-full"),\n\t\t\t\tsave: page.getByRole("button", { name: "Save" }),\n\t\t\t};\n\t\t\tawait expect(targets.save).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
		},
		{
			name: "allows semantic Playwright locator composition",
			code: '\n\t\t\tawait expect(page.getByRole("row").filter({ has: page.getByText("Worker Name") })).toBeVisible();\n\t\t\tawait expect(page.getByRole("row").filter({ hasNot: page.getByRole("button", { name: "Delete" }) })).toBeVisible();\n\t\t\tconst activeClientFilters = (page) => page.getByRole("list", { name: "Active client filters" });\n\t\t\tawait expect(activeClientFilters(page)).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
		},
		{
			name: "allows semantic locators and domain values through const collections and for-of aliases",
			code: '\n\t\t\tconst links = [\n\t\t\t\tpage.getByRole("link", { name: "Organisation" }),\n\t\t\t\tpage.getByRole("link", { name: "Scheduling" }),\n\t\t\t];\n\t\t\tfor (const link of links) {\n\t\t\t\tawait expect(link).toBeAttached();\n\t\t\t}\n\t\t\tconst statuses = ["blocked", "active"];\n\t\t\tfor (const status of statuses) {\n\t\t\t\texpect(status).toMatch(/blocked|active/);\n\t\t\t}\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
		},
		{
			name: "allows domain values that happen to resemble Tailwind utilities",
			code: '\n\t\t\tconst status = "hidden";\n\t\t\texpect(status).toBe("hidden");\n\t\t\tconst copiedStatus = status;\n\t\t\texpect(copiedStatus).toEqual("hidden");\n\t\t\tconst display = "block";\n\t\t\texpect(display).toStrictEqual("block");\n\t\t\texpect("relative").toBe("relative");\n\t\t\tfunction checkDomainClasses(classes) {\n\t\t\t\texpect(classes).toContain("Worker safety");\n\t\t\t}\n\t\t\tconst schedulingCode = "gap-x-2";\n\t\t\texpect(schedulingCode).toBe("gap-x-2");\n\t\t\tconst animationName = "transition-colors";\n\t\t\texpect(animationName).toBe("transition-colors");\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
		},
		{
			name: "does not flag class manipulation, product copy, or lint-message assertions",
			code: '\n\t\t\telement.classList.add("whitespace-nowrap");\n\t\t\tif (element.classList.contains("whitespace-nowrap")) element.remove();\n\t\t\texpect(element.classList.contains(classToken)).toBe(true);\n\t\t\texpect(element.getAttribute("class")).toContain("theme-transitioning");\n\t\t\texpect(schedule.class).toBe("block");\n\t\t\texpect(html).toContain("Results per Page");\n\t\t\texpect(html).toContain("Value hidden");\n\t\t\texpect(html).toContain("hidden");\n\t\t\texpect(html).toContain("flex");\n\t\t\texpect(html).toContain("table-filter-chips");\n\t\t\texpect(html).toContain("row-level changes");\n\t\t\texpect(html).toContain("order-history");\n\t\t\texpect(html).toContain("rounded");\n\t\t\texpect(html).toContain("transition");\n\t\t\texpect(container.querySelector("table")).not.toBeNull();\n\t\t\texpect(container.querySelector(\'[data-label="table"]\')).not.toBeNull();\n\t\t\texpect(container.querySelector(\'[data-label="prefix .h-11"]\')).not.toBeNull();\n\t\t\texpect(container.querySelector(\'[class*="card"]\')).not.toBeNull();\n\t\t\texpect(container.querySelector(".product-card")).not.toBeNull();\n\t\t\texpect(container.querySelector(".order-history")).not.toBeNull();\n\t\t\texpect(container.querySelector(".row-level")).not.toBeNull();\n\t\t\texpect(container.querySelector(".relative-time")).not.toBeNull();\n\t\t\texpect(getClassLabel()).toBe("hidden");\n\t\t\texpect(() => element.classList.contains("w-full")).not.toThrow();\n\t\t\tawait expect(locator).toHaveClass([className]);\n\t\t\tawait expect(locator).toHaveClass(/dark/);\n\t\t\tawait expect(locator).toHaveClass(new RegExp(theme));\n\t\t\tawait expect.soft(message).toContain("hidden");\n\t\t\tawait expect.poll(() => status).toBe("flex");\n\t\t\texpect(messages[0].message).toContain("\'shadow-lg\'");\n\t\t\tconst cls = status;\n\t\t\texpect(cls).toContain("w-full");\n\t\t\tconst cn = (value) => value;\n\t\t\texpect(cn("w-full")).toBe("w-full");\n\t\t\tconst output = status;\n\t\t\texpect(output).toContain("w-full");\n\t\t\texpect(page.locator(".product-card")).toBeVisible();\n\t\t\tpage.locator(".w-full").click();\n\t\t\tfunction getWorkerClass() { return "Gold"; }\n\t\t\texpect(getWorkerClass()).toBe("Gold");\n\t\t\tconst model = { getClass: () => "Gold" };\n\t\t\texpect(model.getClass()).toBe("Gold");\n\t\t\tconst schedule = { className: "Gold" };\n\t\t\texpect(schedule.className).toBe("Gold");\n\t\t\tconst response = { classList: ["Gold"] };\n\t\t\texpect(response.classList).toContain("Gold");\n\t\t\texpect(response.classList).toHaveLength(1);\n\t\t\texpect(schedule.className).toBeNull();\n\t\t\tconst firstPredicate = secondPredicate;\n\t\t\tconst secondPredicate = firstPredicate;\n\t\t\texpect(firstPredicate).toBe(true);\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			options: [{ semanticClassValues: ["dark", "theme-transitioning"] }],
		},
		{
			name: "allows explicitly named visual specs",
			code: '\n\t\t\t\tawait expect(locator).toHaveStyle({ color: "red" });\n\t\t\t\tconst color = window.getComputedStyle(element).color;\n\t\t\t',
			filename: "/repo/packages/web/tests/e2e/shell.visual.spec.ts",
		},
		{
			name: "allows documented local exceptions",
			code: '\n\t\t\t// @allow-brittle-test-style-assertion verifies an accessible contrast boundary.\n\t\t\tconst color = window.getComputedStyle(element).color;\n\t\t\t// @allow-brittle-test-style-assertion verifies the class used by the visual contract.\n\t\t\texpect(element.classList.contains("whitespace-nowrap")).toBe(true);\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
		},
		{
			name: "allows documented class assertions in visual specs",
			code: '\n\t\t\t\texpect(element.classList.contains("whitespace-nowrap")).toBe(true);\n\t\t\t\texpect(html).toContain(\'class="min-h-[222px]"\');\n\t\t\t',
			filename: "/repo/packages/web/tests/e2e/skeleton.layout.spec.ts",
		},
		{
			name: "treats project theme-color utilities as ordinary text without semanticClassTokens",
			code: '\nawait expect(page.locator("div.bg-card")).toBeVisible();\n',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
		},
	],
	invalid: [
		{
			name: "rejects exact CSS matchers in ordinary tests",
			code: '\n\t\t\tawait expect(locator).toHaveCSS("background-color", "rgb(255, 255, 255)");\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "cssMatcher" }],
		},
		{
			name: "rejects computed style reads and element style mutation in ordinary tests",
			code: '\n\t\t\tconst color = window.getComputedStyle(element).color;\n\t\t\telement.style.color = "red";\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "computedStyle" }, { messageId: "elementStyle" }],
		},
		{
			name: "rejects asserted classList checks and Tailwind tokens in HTML strings",
			code: '\n\t\t\texpect(element.classList.contains("whitespace-nowrap")).toBe(true);\n\t\t\texpect(element?.classList.contains("w-full")).not.toBe(false);\n\t\t\texpect(element.classList?.contains("h-11")).toBe(true);\n\t\t\texpect(html).toContain(\'class="whitespace-nowrap"\');\n\t\t\texpect(html).not.toContain(\'class="min-h-[222px]"\');\n\t\t\texpect(html).toContain(\'className="px-0"\');\n\t\t\texpect(html).toContain(\'class="mt-6"\');\n\t\t\texpect(html).toContain(\'class="cursor-pointer"\');\n\t\t\texpect(html).toContain(\'class="truncate"\');\n\t\t\texpect(element.className).toContain("w-full");\n\t\t\texpect(element.getAttribute("class")).not.toContain("bg-red-50");\n\t\t\tawait expect(locator).toHaveClass(/truncate/);\n\t\t\texpect(container.querySelector(".h-11")).not.toBeNull();\n\t\t\texpect(container.querySelector("span.truncate")).not.toBeNull();\n\t\t\texpect(container).toHaveAttribute("class", "w-full");\n\t\t\tawait expect(locator).toHaveClass(["hidden", "md:block"]);\n\t\t\tawait expect.poll(() => element.classList.contains("w-full")).toBe(true);\n\t\t\texpect(element.className).toContain("bg-[color:red]");\n\t\t\texpect(element).toHaveClass("md:w-[length:10px]");\n\t\t\texpect(classNames).toEqual(["h-11", "w-full"]);\n\t\t\texpect(container.querySelector(".product-card.w-full")).not.toBeNull();\n\t\t\tawait expect(locator).toHaveClass(new RegExp("w-full"));\n\t\t\texpect(element.classList).toContain("w-full");\n\t\t\tawait expect(locator).toHaveClass(/\\btruncate\\b/);\n\t\t\texpect(element.className).toMatch(/\\bw-full\\b/);\n\t\t\texpect(classes).toContain("w-full");\n\t\t\texpect(element.classList.value).toContain("w-full");\n\t\t\texpect(element.className).toEqual(expect.stringContaining("w-full"));\n\t\t\texpect(element.className).toEqual(expect.stringMatching(/\\btruncate\\b/));\n\t\t\texpect(container.querySelector(".-mt-6")).not.toBeNull();\n\t\t\texpect(element).toHaveAttribute("class", expect.stringContaining("w-full"));\n\t\t\texpect(element.classList).toEqual(expect.arrayContaining(["w-full"]));\n\t\t\tawait expect(locator).toHaveClass(RegExp("w-full"));\n\t\t\texpect(element.className).toMatch(RegExp("w-full"));\n\t\t\texpect(element.classList.contains("selected")).toBe(true);\n\t\t\texpect(element.className).toContain("selected-surface");\n\t\t\texpect(page.locator(\'[class~="w-full"]\')).toBeVisible();\n\t\t\texpect(container.querySelector(\'[class="truncate"]\')).not.toBeNull();\n\t\t\texpect(element.className).toBe("");\n\t\t\texpect(element.getAttribute("class")).toEqual("");\n\t\t\texpect(element).toHaveClass("");\n\t\t\texpect(element).toHaveAttribute("class", "");\n\t\t\texpect(element.className.split(/s+/)).toContain("w-full");\n\t\t\tconst normalizedClasses = element.className.split(/s+/);\n\t\t\texpect(normalizedClasses).toContain("w-full");\n\t\t\texpect(element.classList).toHaveLength(0);\n\t\t\texpect(element.className).toHaveLength(12);\n\t\t\texpect(element.getAttribute("class")).toBeNull();\n\t\t\texpect(element).not.toHaveAttribute("class");\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
			],
		},
		{
			name: "rejects standalone and responsive utilities across expectation variants",
			code: '\n\t\t\texpect(element).toHaveClass("hidden");\n\t\t\texpect(element.classList.contains("relative")).toBe(true);\n\t\t\texpect(element).toHaveClass("md:block");\n\t\t\texpect(element).toHaveClass("shrink-0");\n\t\t\texpect(element).toHaveClass("ring-2");\n\t\t\texpect(element).toHaveClass("size-4");\n\t\t\texpect(element).toHaveClass("translate-x-1");\n\t\t\texpect(element).toHaveClass("divide-y");\n\t\t\texpect(element).toHaveClass("rounded");\n\t\t\texpect(element).toHaveClass("transition");\n\t\t\texpect(element).toHaveClass("text-sm");\n\t\t\texpect(element).toHaveClass("rounded-md");\n\t\t\texpect(element).toHaveClass("font-medium");\n\t\t\texpect(element).toHaveClass("opacity-50");\n\t\t\texpect(element.classList.contains("items-center")).toBe(true);\n\t\t\texpect(container.querySelector(".flex-1")).not.toBeNull();\n\t\t\texpect(element).toHaveClass("bg-red-950/40");\n\t\t\texpect(element).toHaveClass("dark:bg-red-950/40");\n\t\t\texpect(element).toHaveClass("text-red-500/50");\n\t\t\texpect(element).toHaveClass("border-red-200");\n\t\t\texpect(element).toHaveClass("ring-offset-2");\n\t\t\texpect(element).toHaveClass("sm:-mt-6");\n\t\t\texpect(element).toHaveClass("hover:-translate-x-1");\n\t\t\texpect(element).toHaveClass("w-1/2");\n\t\t\texpect(element).toHaveClass("sr-only");\n\t\t\texpect(element).toHaveClass("aspect-video");\n\t\t\texpect(classes!).toContain("w-full");\n\t\t\texpect(element).toHaveClass("w-[calc(100%-1rem)]");\n\t\t\texpect(element).toHaveClass("grid-cols-[repeat(auto-fit,minmax(10rem,1fr))]");\n\t\t\texpect(element.classList.contains("hover:bg-accent")).toBe(true);\n\t\t\tawait expect.soft(locator).toHaveClass("truncate");\n\t\t\tawait expect.poll(() => element.className).toContain("w-full");\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
			],
		},
		{
			name: "rejects low-ambiguity utilities in bare rendered-markup assertions",
			code: '\n\t\t\texpect(html).toContain("whitespace-nowrap");\n\t\t\texpect(html).not.toContain("w-fit");\n\t\t\texpect(html).toContain("md:min-h-[222px]");\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "rejects exact utility strings returned by class helpers",
			code: '\n\t\t\t\texpect(getDocumentPreviewViewportClass("pdf")).toBe("h-[82vh] min-h-[36rem]");\n\t\t\t\texpect(getDocumentPreviewViewportClass("text")).toBe("h-[70vh]");\n\t\t\t\texpect(getWorkerClass()).toBe("w-full");\n\t\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "rejects aliased class values and multiline class attributes",
			code: '\n\t\t\tconst cls = element.className;\n\t\t\tconst copiedClass = cls;\n\t\t\texpect(copiedClass).toContain("w-full");\n\t\t\t\tconst attributeClass = element.getAttribute("class");\n\t\t\t\texpect(attributeClass).toContain("selected-surface");\n\t\t\t\tconst presentation = { className: "w-full" };\n\t\t\t\texpect(presentation.className).toBe("w-full");\n\t\t\t\texpect(html).toContain(`class="\n\t\t\t\t\tselected-surface"`);\n\t\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
			],
		},
		{
			name: "rejects class assertions through rendered-markup aliases",
			code: '\n\t\t\tconst output = renderToStaticMarkup(view);\n\t\t\tconst copiedOutput = output;\n\t\t\texpect(copiedOutput).toContain(\'class="w-full"\');\n\t\t\tconst serialized = element.outerHTML;\n\t\t\texpect(serialized).toContain("whitespace-nowrap");\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "rejects boolean-wrapped class assertions",
			code: '\n\t\t\texpect(element.className.includes("w-full")).toBe(true);\n\t\t\texpect(element.className === "w-full").toBe(true);\n\t\t\tconst cls = element.className;\n\t\t\texpect(cls.indexOf("w-full") >= 0).toBe(true);\n\t\t\texpect(/w-full/.test(cls)).toBe(true);\n\t\t\tconst hasUtility = element.classList.contains("w-full");\n\t\t\tconst copiedPredicate = hasUtility;\n\t\t\texpect(copiedPredicate).toBe(true);\n\t\t\tconst matchesUtility = /w-full/.test(element.className);\n\t\t\texpect(matchesUtility).toBe(true);\n\t\t\texpect(element.matches(".w-full")).toBe(true);\n\t\t\texpect(container.getElementsByClassName("w-full")).toHaveLength(1);\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
			],
		},
		{
			name: "rejects utility-class Playwright locators inside assertions",
			code: '\n\t\t\t\texpect(page.locator(".w-full")).toBeVisible();\n\t\t\t\tawait expect(page.locator("span.truncate")).toHaveCount(1);\n\t\t\t\tconst workerCard = page.locator(".rounded-lg.border");\n\t\t\t\tawait expect(workerCard).toBeVisible();\n\t\t\t\tconst workerName = workerCard.getByText("Worker Name");\n\t\t\t\tawait expect(workerName).toBeVisible();\n\t\t\t\tawait expect(page.locator("tr").filter({ has: page.locator(".w-full") })).toBeVisible();\n\t\t\t\tawait expect(page.locator("tr").filter({ hasNot: page.locator("span.truncate") })).toHaveCount(0);\n\t\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
			],
		},
		{
			name: "rejects project theme-color utilities in Playwright locators",
			code: '\n\t\t\tawait expect(page.locator("div.bg-card")).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			options: [
				{
					semanticClassTokens: [
						"accent",
						"accent-foreground",
						"action-hover",
						"action-ink",
						"action-surface",
						"background",
						"border",
						"brand",
						"brand-foreground",
						"card",
						"card-foreground",
						"checkbox-border",
						"checkbox-checked",
						"checkbox-icon",
						"chrome",
						"chrome-active",
						"chrome-border",
						"chrome-foreground",
						"chrome-hover",
						"chrome-muted-foreground",
						"control",
						"control-active",
						"control-border",
						"control-hover",
						"destructive",
						"destructive-foreground",
						"disabled-border",
						"disabled-ink",
						"disabled-surface",
						"foreground",
						"input",
						"interactive-link",
						"interactive-link-decoration",
						"interactive-link-hover",
						"muted",
						"muted-foreground",
						"popover",
						"popover-foreground",
						"primary",
						"primary-foreground",
						"progress",
						"progress-foreground",
						"progress-surface",
						"ring",
						"row-hover",
						"row-selected",
						"row-selected-border",
						"secondary",
						"secondary-foreground",
						"tab-active",
						"tab-list",
					],
				},
			],
			errors: [{ messageId: "classAssertion" }],
		},
		{
			name: "rejects Tailwind selectors hidden in XPath and locator helpers",
			code: '\n\t\t\texpect(page.locator("xpath=ancestor::div[contains(@class, \'bg-card\')][1]")).toBeVisible();\n\t\t\tconst getCard = () => page.locator(".w-full");\n\t\t\tconst card = getCard();\n\t\t\texpect(card).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			options: [
				{
					semanticClassTokens: [
						"accent",
						"accent-foreground",
						"action-hover",
						"action-ink",
						"action-surface",
						"background",
						"border",
						"brand",
						"brand-foreground",
						"card",
						"card-foreground",
						"checkbox-border",
						"checkbox-checked",
						"checkbox-icon",
						"chrome",
						"chrome-active",
						"chrome-border",
						"chrome-foreground",
						"chrome-hover",
						"chrome-muted-foreground",
						"control",
						"control-active",
						"control-border",
						"control-hover",
						"destructive",
						"destructive-foreground",
						"disabled-border",
						"disabled-ink",
						"disabled-surface",
						"foreground",
						"input",
						"interactive-link",
						"interactive-link-decoration",
						"interactive-link-hover",
						"muted",
						"muted-foreground",
						"popover",
						"popover-foreground",
						"primary",
						"primary-foreground",
						"progress",
						"progress-foreground",
						"progress-surface",
						"ring",
						"row-hover",
						"row-selected",
						"row-selected-border",
						"secondary",
						"secondary-foreground",
						"tab-active",
						"tab-list",
					],
				},
			],
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "rejects locator helpers hidden behind control flow",
			code: '\n\t\t\tfunction getTarget() {\n\t\t\t\tif (compact) return page.locator(".w-full");\n\t\t\t\treturn page.getByRole("row");\n\t\t\t}\n\t\t\tconst getConditionalTarget = () => compact ? page.locator(".w-full") : page.getByRole("row");\n\t\t\tconst getLogicalTarget = () => compact && page.locator(".w-full");\n\t\t\tawait expect(getTarget()).toBeVisible();\n\t\t\tawait expect(getConditionalTarget()).toBeVisible();\n\t\t\tawait expect(getLogicalTarget()).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "rejects static selector arguments passed through locator helpers",
			code: '\n\t\t\tconst getArrowTarget = (selector) => page.locator(selector);\n\t\t\tfunction getFunctionTarget(selector) {\n\t\t\t\treturn page.locator(selector);\n\t\t\t}\n\t\t\tawait expect(getArrowTarget(".w-full")).toBeVisible();\n\t\t\tawait expect(getFunctionTarget(".truncate")).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "resolves only the accessed locator-helper property",
			code: '\n\t\t\tconst targets = {\n\t\t\t\tcard: () => page.locator(".w-full"),\n\t\t\t\tsave: page.getByRole("button", { name: "Save" }),\n\t\t\t};\n\t\t\tawait expect(targets.card()).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }],
		},
		{
			name: "rejects axis-qualified gap utilities",
			code: '\n\t\t\tawait expect(page.locator(".gap-x-2")).toBeVisible();\n\t\t\tawait expect(page.locator(".gap-y-2")).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "rejects common unambiguous Tailwind selectors",
			code: '\n\t\t\tawait expect(page.locator(".bg-white")).toBeVisible();\n\t\t\tawait expect(page.locator(".bg-black")).toBeVisible();\n\t\t\tawait expect(page.locator(".text-white")).toBeVisible();\n\t\t\tawait expect(page.locator(".border-transparent")).toBeVisible();\n\t\t\tawait expect(page.locator(".transition-colors")).toBeVisible();\n\t\t\tawait expect(page.locator(".grid-flow-row")).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
			],
		},
		{
			name: "rejects class tokens hidden behind immutable aliases",
			code: '\n\t\t\tconst utility = "w-full";\n\t\t\tconst utilitySuffix = "full";\n\t\t\tconst interpolatedUtility = `w-${utilitySuffix}`;\n\t\t\tconst selector = `div.${utility}`;\n\t\t\texpect(element.className).toContain(utility);\n\t\t\texpect(element).toHaveClass(utility);\n\t\t\texpect(element.classList.contains(interpolatedUtility)).toBe(true);\n\t\t\tawait expect(page.locator(selector)).toBeVisible();\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
				{ messageId: "classAssertion" },
			],
		},
		{
			name: "rejects negated asymmetric class matchers",
			code: '\n\t\t\texpect(element.className).toEqual(expect.not.stringContaining("w-full"));\n\t\t\texpect(element.className).toEqual(expect.not.stringMatching(/truncate/));\n\t\t\texpect(element.classList).toEqual(expect.not.arrayContaining(["w-full"]));\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "rejects normalized classList assertions",
			code: '\n\t\t\texpect(Array.from(element.classList)).toContain("w-full");\n\t\t\texpect([...element.classList]).toContain("w-full");\n\t\t\texpect(element.classList.item(0)).toBe("w-full");\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "rejects utility-class locators through const collections and for-of aliases",
			code: '\n\t\t\tconst strip = page.locator(".overflow-x-auto");\n\t\t\tconst links = [\n\t\t\t\tstrip.getByRole("link", { name: "Organisation" }),\n\t\t\t\tstrip.getByRole("link", { name: "Scheduling" }),\n\t\t\t];\n\t\t\tfor (const link of links) {\n\t\t\t\tawait expect(link).toBeAttached();\n\t\t\t}\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }],
		},
		{
			name: "rejects exact output from canonical class helpers",
			code: '\n\t\t\timport { cn as mergeClasses } from "@/lib/utils";\n\t\t\timport clsx from "clsx";\n\t\t\timport { twMerge } from "tailwind-merge";\n\t\t\tconst mergeAlias = twMerge;\n\t\t\texpect(mergeClasses("w-full")).toBe("w-full");\n\t\t\texpect(clsx("hidden")).toEqual("hidden");\n\t\t\texpect(mergeAlias("w-full")).toBe("w-full");\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "distinguishes bound class values from similarly named domain data",
			code: '\n\t\t\t{\n\t\t\t\tconst classes = ["w-full"];\n\t\t\t\texpect(classes).toContain("w-full");\n\t\t\t}\n\t\t\t{\n\t\t\t\tconst className = "h-11 w-full";\n\t\t\t\texpect(className).toBe("h-11 w-full");\n\t\t\t}\n\t\t\t{\n\t\t\t\tconst classes = ["Worker safety"];\n\t\t\t\texpect(classes).toContain("Worker safety");\n\t\t\t}\n\t\t\t{\n\t\t\t\tconst className = "Gold";\n\t\t\t\texpect(className).toBe("Gold");\n\t\t\t}\n\t\t',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }, { messageId: "classAssertion" }],
		},
		{
			name: "flags configured semantic class values once they leave semanticClassValues",
			code: '\nexpect(element.getAttribute("class")).toContain("theme-transitioning");\n',
			filename: "/repo/packages/web/tests/e2e/example.spec.ts",
			errors: [{ messageId: "classAssertion" }],
		},
	],
});
